package co.edu.escuelaing.techcup.teams.domain.enums;

public enum AuditActionType {
    TEAM_CREATED,
    TEAM_UPDATED,
    TEAM_DELETED,
    INVITATION_SENT,
    INVITATION_ACCEPTED,
    INVITATION_REJECTED,
    PLAYER_REMOVED,
    CAPTAINCY_TRANSFER_INITIATED,
    CAPTAINCY_TRANSFER_ACCEPTED,
    CAPTAINCY_TRANSFER_REJECTED,
    CAPTAINCY_APPLICATION_SENT
}
