spring:
  application:
    name: cc-teams-service
  profiles:
    active: dev

server:
  port: 11712

app:
  jwt:
    secret: ${JWT_SECRET:super-secret-key-that-is-at-least-256-bits-long-for-hs256}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: cc-teams-service
    description: Microservicio de equipos para TechCup 2026
    version: 0.0.1-SNAPSHOT

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs
