spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/teams_db

logging:
  level:
    co.edu.escuelaing.techcup: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG
